config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  # I have to find a better way to do the following routing:
  # a) This code block 
  resources :moves do
    resources :boxes, only: [:new, :create]
  end
  resources :boxes, only: [:show, :edit, :update, :destroy]
  
  # b) This code block
  resources :boxes, except: [:new, :show, :create, :edit, :update, :destroy] do
    resources :items, only: [:new, :create]
    member do
      get 'print_label'
    end
  end
  resources :items, only: [:show, :edit, :update, :destroy]
  
  root 'moves#index'
end

app/models/box.rb
class Box < ActiveRecord::Base
    
    belongs_to :move
    belongs_to :user
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
    
    belongs_to :box
    belongs_to :user
    
    has_attached_file :image, styles: { large: "500x500#", medium: "300x300#", thumb: "100x100#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    validates_attachment_presence :image
end

app/models/move.rb
class Move < ActiveRecord::Base
    
    has_many :boxes, dependent: :destroy
    belongs_to :user
    
    validates_presence_of :name, :to, :from
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :omniauthable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :moves, dependent: :destroy
  has_many :boxes, dependent: :destroy
  has_many :items, dependent: :destroy
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.extra.raw_info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_params, if: :devise_controller?
  
  protected
  
  def configure_permitted_params
    
    # parameters allowed to pass for account creation
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name)}
    
    # parameters allowed to pass for account update
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name)}
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
    
    before_action :authenticate_user!
    before_action :set_move_new, only: [:new, :create]
    before_action :set_move_update, except: [:new, :create]
    before_action :set_box, except: [:new, :create]
    before_action :fetch_items, only: [:show, :print_label]
    
    def show
    end
    
    def new
        @box = @move.boxes.build
    end
    
    def create
        @box = @move.boxes.build(box_params)
        
        @box.user_id = current_user.id
        
        if @box.save
            redirect_to @move, notice: "Successfully created box '#{@box.name}'"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @box.update_attributes(box_params)
            redirect_to @move, notice: "Successfully updated box '#{@box.name}'"
        else
            render 'edit'
        end
    end
    
    def destroy
        @box.destroy
        redirect_to @move, notice: "Successfully deleted box"
    end
    
    # action to generate print label for box
    def print_label
        qr_string = url_for(@box)
        @qrcode = RQRCode::QRCode.new(qr_string).to_img.resize(225,225).to_data_url
    end
    
    private
    
    def set_move_new
        @move = Move.find(params[:move_id])
    end
    
    def set_move_update
        @box = Box.find(params[:id])
        @move_id = @box.move_id
        @move = Move.find(@move_id)
    end
    
    def set_box
        @box = Box.find(params[:id])
    end
    
    def fetch_items
        @items = Item.where(box_id: @box.id).order("created_at DESC")
        @item_count = @items.count
    end
    
    def box_params
        params.require(:box).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
        
    before_action :authenticate_user!
    before_action :set_box_new, only: [:new, :create]
    before_action :set_box_update, only: [:show, :edit, :update, :destroy]
    # before_action :set_move
    before_action :set_item, only: [:show, :edit, :update, :destroy]
    
    def show
    end
    
    def new
        @item = @box.items.build
    end
    
    def create
        @item = @box.items.build(item_params)
        
        @item.move_id = @box.move_id
        @item.user_id = current_user.id
        
        if @item.save
            redirect_to @box, notice: "Successfully added item '#{@item.name}'"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @item.update_attributes(item_params)
            redirect_to @box, notice: "Successfully updated item"
        else
            render 'edit'
        end
    end
    
    def destroy
        @item.destroy
        redirect_to @box, notice: "Successfully deleted item"
    end
    
    private
    
    def set_box_new
        @box = Box.find(params[:box_id])
    end
    
    def set_box_update
        @item = Item.find(params[:id])
        @box_id = @item.box_id
        @box = Box.find(@box_id)
    end
    
    def set_item
        @item = Item.find(params[:id])
    end

    def item_params
        params.require(:item).permit(:name, :image)
    end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
    
    before_action :authenticate_user!
    before_action :set_move, except: [:index, :new, :create]
    
    def index
        @moves = Move.where(user_id: current_user.id).order(created_at: :DESC)
    end
    
    def show
        @boxes = Box.where(move_id: @move.id).order("created_at DESC")
        @box_count = @boxes.count
    end
    
    #view for the create method
    def new
        @move = current_user.moves.build
    end
    
    def create
        @move = current_user.moves.build(move_params)
        
        if @move.save
            redirect_to @move, notice: "Successfully created move '#{@move.name}'"
        else
            render 'new'
        end
    end
    
    #view for update method
    def edit
    end
    
    def update
        if @move.update(move_params)
            redirect_to @move, notice: "Successfully updated move"
        else
            render 'edit'
        end
    end
    
    def destroy
        @move = Move.find(params[:id])
        @move.destroy
        redirect_to root_path, notice: "Successfully deleted move"
    end
    
    private
    
    def set_move
        @move = Move.find(params[:id])
    end
    
    def move_params
        params.require(:move).permit(:name, :from, :to)
    end
    
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def all
        user = User.from_omniauth(request.env['omniauth.auth'])
        
        if user.persisted?
            flash.notice = "Signed in!"
            sign_in_and_redirect user
        else
            session["devise.user_attributes"] = user.attributes
            redirect_to new_user_registration_url
        end
    end
    alias_method :facebook, :all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/boxes/edit.html.erb
<%= link_to @move, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>

<div class="form-container">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for(@box, html: { class: 'form-horizontal'}) do |f| %>
            <%= f.input :name, label: false %>
            <%= f.button :submit, class: "btn btn-success btn-block" %>
        <% end %> 
    </div>
</div>

app/views/boxes/new.html.erb
<%= link_to @move, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>

<div class="form-container">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for([@move, @box], html: { class: 'form-horizontal'}) do |f| %>
            <%= f.input :name, label: false, placeholder: "Box Name" %>
            <%= f.button :submit, class: "btn btn-success btn-lg btn-block" %>
        <% end %>
    </div>
</div>

app/views/boxes/print_label.html.erb
<div class="container">
    <%= link_to box_path(@box), class: "internal-nav" do %>
        <i class="fa fa-arrow-left"></i>
        Back
    <% end %>
    <%= link_to "PRINT LABELS", "#", id: "print-button", class: "btn btn-success btn-block", :onclick => "window.print();return false;" %>
    <% 6.times do %>
        <div id="label-container" class="col-md-6">
            <div class="label-wrapper">
                <div class="media">
                  <div class="media-body">
                    <div id="qr-wrapper">
                        <%= image_tag @qrcode %>
                    </div>
                    <div class="box-info">
                       <h4 id="print-logo">Boxr</h4>
                        <p class="box-stat">Move: <strong><%= @move.name %></strong></p>
                        <p class="box-stat">Box: <strong><%= @box.name %></strong></p>
                        <p class="box-stat">Items: <strong><%= @item_count %></strong></p> 
                    </div>
                  </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/boxes/show.html.erb
<div class="box-show">
    <div class="jumbotron">
        <%= link_to @move, class: "internal-nav" do %>
            <i class="fa fa-arrow-left"></i>
            Back
        <% end %>
        <div class="jumbotron-media-links">
            <%= link_to "Edit Box", edit_box_path(@box) %> | 
            <%= link_to "Delete Box", @box, method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
        <div class="move-container">
            <div class="media">
              <div class="media-body">
                <h2 class="media-heading"><%= @box.name %></h2>
                <h3 class="box-info">
                    <%= pluralize(@item_count, 'Item') %>
                </h3>
                <div id="print-label" class="stats">
                    <%= link_to print_label_box_path(@box) do %>
                        <i class="fa fa-qrcode"></i> 
                        Print Label
                    <% end %>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

<div>
    <% if @items.empty? %>
        <div class="empty-state-container">
            <div class="alert alert-info">
                <p>There are no items yet. Add them below.</p>
            </div>
        </div>
    <% end %>
    
    <div class="btn-container">
        <%= link_to new_box_item_path(@box), class: "btn btn-block" do %>
            <i class="fa fa-plus"></i>
            Add Item
        <% end %>
    </div>
    
    <div class="item-container">
        <% @items.each do |item| %>
            <%= link_to item_path(item) do %>
                <div class="col-md-3">
                    <div class="media">
                        <div class="image-wrapper">
                            <%= image_tag item.image.url(:medium), class: "item-image" %>
                        </div>
                        <div class="media-body">
                            <h2 class="media-heading"><%= item.name %></h2>
                            <p class="secondary-heading">Added <%= time_ago_in_words(item.created_at) %> ago</p>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
    
</div>

app/views/items/edit.html.erb
<%= link_to @box, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>

<div class="form-container">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for(@item, html: { class: "form-horizontal" }) do |f| %>
            <%= f.input :name, label: false %>
            <%= f.button :submit, class: "btn btn-success btn-block" %>
        <% end %>
    </div>
</div>

app/views/items/new.html.erb
<%= link_to @box, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>

<div class="form-container">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for([@box, @item], html: { class: "form-horizontal" }) do |f| %>
            <%= f.file_field :image %>
            <%= f.input :name, label: false, required: true, error: "Cant' be blank", placeholder: "Item Name" %>
            <%= button_tag "Add Item", class: "btn btn-success btn-lg btn-block", data: { disable_with: "<i class='fa fa-spinner fa-pulse'></i> Adding Item..." } %>
        <% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default main-header">
  <div class="container-fluid">
    <div class="navbar-header">
      <div id="logo"><%= link_to "Boxr", root_path %></div>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"><i class="fa fa-bars"></i></button>
    </div>
    <div class="navbar-right">
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <p class="navbar-text"><%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path %></p>
              <li><%= link_to "New Move", new_move_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </ul>
      </div>
     </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
   <%= content_tag(:div, msg, id: "notice-wrapper") %>
<% end %>
  
<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
</div>

<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('#notice-wrapper').fadeOut("slow", function() {
        $this.remove();
      });
    }, 2500 );
  });
</script>

</body>
</html>

app/views/moves/_form.html.erb
<div class="form-container">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for(@move, html: { class: 'form-horizontal'}) do |f| %>
            <%= f.input :name, label: false, error: "What's the name of the move?", placeholder: "Enter move name"%>
            <%= f.input :from, label: false, error: "Where are you moving from?", placeholder: "Where are you moving from?" %>
            <%= f.input :to, label: false, error: "Where are you moving to?", placeholder: "Where are you moving to?" %>
            <%= f.button :submit, class: "btn btn-success btn-lg btn-block" %>
        <% end %>
    </div>
</div>

app/views/moves/edit.html.erb
<%= link_to @move, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>
<%= render 'form' %>

app/views/moves/index.html.erb
<% if @moves.empty? %>
    <div class="empty-state-container">
       <div class="alert alert-info">
            <p>You have no moves scheduled.</p>
        </div> 
    </div>
<% end %>

<div class="btn-container">
    <%= link_to new_move_path, class: "btn btn-block" do %>
        <i class="fa fa-plus"></i>
        New Move
    <% end %>
</div>

<div class="move-container">
    <% @moves.each do |move| %>
        <%= link_to move do %>
            <div class="col-md-4">
                <div class="media">
                  <div class="media-body">
                    <h2 class="media-heading"><%= move.name %></h2>
                    <h3 class="box-info">
                        <%= move.from %>
                        <i class="fa fa-arrow-right"></i>
                        <%= move.to %>
                    </h3>
                  </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/moves/new.html.erb
<%= link_to root_path, class: "internal-nav" do %>
    <i class="fa fa-arrow-left"></i>
    Cancel
<% end %>
<%= render 'form' %>

app/views/moves/show.html.erb
<div class="jumbotron">
    <%= link_to root_path, class: "internal-nav" do %>
        <i class="fa fa-arrow-left"></i>
        Back
    <% end %>
    <div class="jumbotron-media-links">
        <%= link_to "Edit Move", edit_move_path %> | 
        <%= link_to "Delete Move", @move, method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
    <div class="move-container">
        <div class="media">
          <div class="media-body">
            <h2 class="media-heading"><%= @move.name %></h2>
            <h3 class="box-info">
                <%= @move.from %>
                <i class="fa fa-arrow-right"></i>
                <%= @move.to %>
            </h3>
            <p class="stats"><%= pluralize(@box_count, 'Box') %></p>
          </div>
        </div>
    </div>
</div>

<div>
    <% if @boxes.empty? %>
        <div class="empty-state-container">
           <div class="alert alert-info">
                <p>Planning on moving without boxes? If not add boxes below.</p>
            </div> 
        </div>
    <% end %>
    
    <div class="btn-container">
        <%= link_to new_move_box_path(@move), class: "btn btn-block" do %>
            <i class="fa fa-plus"></i>
            Add Box
        <% end %>
    </div>
    
    <div class="move-container">
        <% @boxes.each do |box| %>
         <%= link_to box_path(box) do %>
             <div class="col-md-4">
                <div class="media">
                  <div class="media-body">
                    <h2 class="media-heading"><%= box.name %></h2>
                  </div>
                  <div class="links">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default"><%= link_to "View", box_path(box) %></button>
                        <button type="button" class="btn btn-default"><%= link_to "Edit", edit_box_path(box) %></button>
                        <button type="button" class="btn btn-default"><%= link_to "Delete", box_path(box), method: :delete, data: { confirm: "Are you sure?" } %></button>
                    </div>
                  </div>
                </div>
             </div>
         <% end %>
        <% end %>
    </div>
</div>